### ISSUE TITLE
Write String Buffer with Padding

### ISSUE THREAD

**Issue by majimboo** [JoshGlazebrook/smart-buffer#1]
Having something like adding have a set of 00 00 00 00 00 00 00 00 00...

and fill it with a string like BLAZE... Where not all bytes will be used, so it can still be 

B L A Z E 00 00 00....

**Comment by p0358** [comment]
@JoshGlazebrook I still think a helper function for this would be very nice. After all it's a library to make our lives easier and the code more readable. And some formats require the string to be of fixed size, rather than null-terminated. Especially that it can be directly mapped to a C struct. Padding it each time with zeroes manually is a little bit tedious.
I think something like
```ts
buff.writeStringFixed("BLAZE", 8);
```
would be ideal, it'd write 5 bytes of the string, and add 3 of padding, so that the total length would be 8. Manual offset could be the 3rd parameter then. Not sure if `writeStringFixed` is the best name idea, but that doesn't matter.

**Comment by p0358** [comment]
For anyone needing this, we made a fork which implements this: https://github.com/harmonytf/smart-buffer

**Comment by JoshGlazebrook** [comment]
Feel free to make a pr and I can merge it in.
